### ISSUE TITLE
Livereload / Webpack

### ISSUE THREAD

**Issue by thodorisbais** [thodorisbais/percircle#35]
Configure [`watch`](https://github.com/toubou91/percircle/blob/master/gulpfile.js#L17) task with [livereload](https://www.npmjs.com/package/gulp-livereload) to automatically monitor files for changes and reload them to a browser.

<em>Current implementation only performs compilation checks.</em>

Alternatively (and preferably, I would also add), we could also move from Gulp to Webpack.
That would take `percircle` to the next step for sure.

**Comment by chris--jones** [comment]
I believe this is addressed by #59 and can be closed once #60 is merged (so that you can actually see the live reload working)
