### ISSUE TITLE
Text not showing up when percent is 0

### ISSUE THREAD

**Issue by whoisme555** [thodorisbais/percircle#55]
Looks like the code checks if(percent) before adding the text, when percent is 0, it won't get added.

I think this should be configurable via option. if (percent || options.forcePercentText) or something.

In my particular case, I'm using this plugin to display letter grades and the % progress to 100% (A+).  If they received a 0, I'd still want to display F, but it gets hidden due to the above conditional.  My current hack is to add .0001 to the % so it's never 0, but that's not very eloquent.

![image](https://user-images.githubusercontent.com/50149901/56980150-9bab7300-6b49-11e9-8ef1-51c96370077c.png)

**Comment by whoisme555** [comment]
I'm not sure if this is maintained at all, but I've modified line 65 of percircle.js to be

![image](https://user-images.githubusercontent.com/50149901/56984236-905d4500-6b53-11e9-8029-2cbd4a628ff6.png)


And added this as part of the configuration to fix it

![image](https://user-images.githubusercontent.com/50149901/56984263-a0752480-6b53-11e9-858b-b859dac6af24.png)

**Comment by thodorisbais** [comment]
Hi @whoisme555 , 

thanks a lot for using `percircle`!

As implied in #43 and #44, `percircle` is not actively maintained anymore. 
That said, we would be more than happy to review a Pull Request with the suggested fix for the issue you just introduced :-)

Regards,
Theo

**Comment by whoisme555** [comment]
Sounds good, I'll look into submitting a pull request when I get some time.

**Comment by thodorisbais** [comment]
Cool!

**Comment by thodorisbais** [comment]
Any update here @whoisme555 ? :-)

**Comment by whoisme555** [comment]
Sorry, got overloaded at work and forgot. I'll put it in my calendar to remind myself when I expect to have more time in a few days!
Sent from Yahoo Mail on Android 
 
  On Mon, May 13, 2019 at 2:22 PM, Thodoris Bais<notifications@github.com> wrote:   
Any update here @whoisme555 ? :-)

**Comment by thodorisbais** [comment]
Are we sure this is an issue?
For me, it looks to be working fine: 
![Screenshot 2019-05-15 at 21 49 51](https://user-images.githubusercontent.com/5684688/57804626-69119500-775b-11e9-81d6-e94b88c0afe8.png)

Which browser are you testing on?

**Comment by whoisme555** [comment]
Latest version of chrome. Not sure how it's working for you, if the percent is 0, it's a falsey value and would never enter the branch of code that displays the text.

Maybe I'm using it wrong?

category.score is a double from 0-100
    On Wednesday, May 15, 2019, 3:50:22 PM EDT, Thodoris Bais <notifications@github.com> wrote:  
 
 
Are we sure this is an issue?
For me, it looks to be working fine:


Which browser are you testing on?

**Comment by whoisme555** [comment]
![image](https://user-images.githubusercontent.com/50149901/57954715-b6a81200-78c1-11e9-86f4-bbff686535eb.png)

![image](https://user-images.githubusercontent.com/50149901/57954724-c0317a00-78c1-11e9-9ec1-abe5232cca73.png)


I'm attaching pictures that didn't get attached when responding via email.

Maybe I'm using it wrong, but the first is my init code, and the next is the output if category.score is ever 0

**Comment by thodorisbais** [comment]
I see, there's maybe something else going wrong with the initialization of `percent`, since you're giving it a dynamic value. However, for now, I would like to accept this solution, so, let's take this discussion further at #56

**Comment by thodorisbais** [comment]
Closed with #56
